#!/usr/bin/env python
#
# Copyright (C) 2022  Vates SAS
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import argparse
import json
import linstor

def dump_kv(controller_uri, group_name, namespace):
    kv = linstor.KV(
        group_name,
        uri=controller_uri,
        namespace=namespace
    )
    print(json.dumps(kv, sort_keys=True, indent=2))

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-u', '--uri', required=True)
    parser.add_argument('-g', '--group-name', required=True)
    parser.add_argument('-n', '--namespace', default='/')
    args = parser.parse_args()
    dump_kv(args.uri, args.group_name, args.namespace)

if __name__ == '__main__':
    main()
